# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0000ff
  secondary: 0054ff
  secondary-dark: 384d54
  muted: 485a60

# Font Families
font:
  primary: '"PT Sans", "Vazir", sans-serif'
  primary-fa: '"Vazir", "PT Sans", sans-serif'
  secondary: '"PT Sans", "Vazir", sans-serif'
  secondary-fa: '"Vazir", "PT Sans", sans-serif'
